-- DROP TABLE IF EXISTS tornadoesP3;

CREATE TABLE "tornadoesTest" (
    "om" INT   NOT NULL,
    "yr" INT   NOT NULL,
	"mo" INT   NOT NULL,
    "dy" INT   NOT NULL,
    "date" date   NOT NULL,
    "time" time   NOT NULL,
    "tz" INT   NOT NULL,
    "st" varchar(64)  NOT NULL,
    "stf" INT   NOT NULL,
    "stn" INT   NOT NULL,
    "mag" INT   NOT NULL,
    "inj" INT   NOT NULL,
    "fat" INT   NOT NULL,
    "loss" FLOAT   NOT NULL,
	"closs" FLOAT   NOT NULL,
	"slat" FLOAT   NOT NULL,
	"slon" FLOAT   NOT NULL,
	"elat" FLOAT   NOT NULL,
	"elon" FLOAT   NOT NULL,
	"len" FLOAT   NOT NULL,
	"wid" INT   NOT NULL,
	"ns" INT   NOT NULL,
	"sn" INT   NOT NULL,
	"sg" INT   NOT NULL,
    "f1" INT   NOT NULL,
	"f2" INT   NOT NULL,
	"f3" INT   NOT NULL,
	"f4" INT   NOT NULL,
	"fc" INT   NOT NULL
);